[package]
name = "nipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.3.2"
clap = { version = "4.5.3", features = ["derive"] }
tempfile = "3.10.1"
